<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
remove_action('genesis_entry_content', 'genesis_do_post_content');
add_action( 'genesis_entry_content', 'vod_content' ); // Add custom loop

function vod_content() {

  // Check for Authorization
  if ( isset( $_COOKIE['isAuthorized'] ) ){

  ?>
    <div class="vod-content">
      <?php
      $level = get_field( 'class_level' );
      $length = get_field( 'length' );
      $instructor = get_field( 'instructor' );
      $language = get_field( 'language' );
      $embed = get_field('vod_embed');
      $props = get_field('props_needed');?>

      <?php echo $embed; ?>

      <div class="vod-header">
        <h2 class="entry-title"><?php echo the_title(); ?></h2>
        <?php
          if ( $level ) {
            echo '<div class="level '. $level . '">' . $level . '</div>';
          }?>
      </div>

      <div class="metaWrap">
        <div class="vod-meta left">
          <?php
          if ( $instructor ) { ?>
            <div class="instructor-image <?php echo $instructor; ?>"></div>
            <div class="instructor">Instructor: <span><?php echo $instructor;?></span> </div>
          <?php }?>

            <div class="lengthlang">Length: <span><?php echo $length; ?> mins</span></div>
            <div class="lengthlang">Language: <span><?php echo $language;?></span></div>

        </div>

        <?php if ($props) : ?>
          <div class="vod-meta right">
            <h2>Suggested Props </h2>
            <p><?php echo $props; ?></p>
          </div>
        <?php endif; ?>
      </div>

    </div>

    <a class="button small green-hollow" href="/vod">&laquo; Back to COD Archives</a>
    <?php
  }
  else {
    ?> <h2>Sorry,</h2>
      <p>Your account must be verified to access Classes on Demand</p>
      <a class="button orange-button small" href="<?php echo site_url();?>/vod">Verify your account here</a>
      <?php
  }
}
genesis();
